### ISSUE TITLE
La moitié des jours fériés n'ont pas de nom

### ISSUE THREAD

**Issue by Albirew** [etalab/jours-feries-france-data#4]
Sur 11 jours fériés en France métropolitaine (je n'ai pas vérifié les autres calendriers), 5 n'ont pour nom que leur date.
Est-il possible de renommer ces fêtes sans gêner la génération automatique?

1er janvier 	-> Nouvel An
1er mai 		-> Fête du travail
8 mai 		-> Fête de la victoire 1945
14 juillet 		-> Fête nationale
11 novembre 	-> Armistice

**Comment by AntoineAugusti** [comment]
Bonjour,

Les noms suivent ce qui est indiqué [dans le code du travail L3133-1](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033020901)

**Comment by Albirew** [comment]
Ah, effectivement...
Dans ce cas...
